version: '3'
services:
  redis:
    container_name: redis_redis
    image: "redis:alpine"
  web:
    container_name: redis_web
    build: .
    ports:
     - "5000:5000"
    depends_on:
      - redis
