version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: celery_redis
  celery:
    container_name: celery_celery
    build: celery
    volumes:
      - ./celery:/code
    depends_on:
      - redis
  web:
    container_name: celery_web
    build: app_with_redis
    ports:
     - "5000:5000"
    depends_on:
      - celery
