version: '3'
services:
  redis:
    image: "redis:alpine"
    container_name: celery_redis
  celery:
    container_name: celery_celery
    build: celery
    volumes:
      - ./celery:/code
    depends_on:
      - redis
    command: celery worker -A tasks -l info -c 2 -Q "celery,urls,add"
  web:
    container_name: celery_web
    build: app_with_redis
    volumes:
      - ./app_with_redis:/code
    ports:
     - "5000:5000"
    depends_on:
      - celery
