# Generated by Django 2.0.6 on 2018-06-14 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Goods', 'verbose_name_plural': 'Goods'},
        ),
    ]
